theme: jekyll-theme-minimal
description: The K-dwarfs Orbited By habitable Exoplanets (KOBE) experiment is an approved legacy program of the Calar Alto Observatory (CAHA) awarded with 175 nights at the 3.5m telescope to use the CARMENES instrument to perform a survey of 50 late-type K-dwarfs to search for planets in their habitable zone
logo: KOBE_logo.jpg
